//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo {
	
	
	public partial class profit {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label exchange1;
		
		protected System.Web.UI.WebControls.Label coin1;
		
		protected System.Web.UI.WebControls.Label profit1;
		
		protected System.Web.UI.WebControls.Label exchange2;
		
		protected System.Web.UI.WebControls.Label coin2;
		
		protected System.Web.UI.WebControls.Label profit2;
		
		protected System.Web.UI.WebControls.Label exchange3;
		
		protected System.Web.UI.WebControls.Label coin3;
		
		protected System.Web.UI.WebControls.Label profit3;
		
		protected System.Web.UI.WebControls.Label exchange4;
		
		protected System.Web.UI.WebControls.Label coin4;
		
		protected System.Web.UI.WebControls.Label profit4;
		
		protected System.Web.UI.HtmlControls.HtmlButton Start;
	}
}
