//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo {
	
	
	public partial class wallet {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label BTC;
		
		protected System.Web.UI.WebControls.Label ETH;
		
		protected System.Web.UI.WebControls.Label ZEC;
		
		protected System.Web.UI.WebControls.Label LTC;
		
		protected System.Web.UI.WebControls.Label BTC_in;
		
		protected System.Web.UI.WebControls.Label ETH_in;
		
		protected System.Web.UI.WebControls.Label ZEC_in;
		
		protected System.Web.UI.WebControls.Label LTC_in;
		
		protected System.Web.UI.HtmlControls.HtmlTable history;
	}
}
